'use client'
import { PageShell } from '@/components/page-shell'
import { SectionCard, StatCard, StatusBadge } from '@/components/blocks'
import { adminNav } from '@/lib/navigation'
import { useDemoStore } from '@/lib/demo-store'

export default function AdminDashboardPage() {
  const store = useDemoStore()
  return <PageShell role="Admin" title="Platform dashboard" subtitle="Lightweight oversight across vendors, grocers, connections, and orders." nav={adminNav.map((n)=>({...n,current:n.href==='/admin/dashboard'}))}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><StatCard label="Total vendors" value={store.vendors.length} /><StatCard label="Total grocers" value={store.grocers.length} /><StatCard label="Pending connections" value={store.connections.filter((c) => c.status === 'pending').length} /><StatCard label="Orders in progress" value={store.orders.filter((o) => ['submitted','modified','confirmed'].includes(o.status)).length} /><StatCard label="Needs attention" value={store.orders.filter((o) => o.status === 'modified').length} tone="attention" /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><SectionCard title="Recent activity"><div className="space-y-3">{store.orderEvents.slice().sort((a,b)=>a.createdAt < b.createdAt ? 1 : -1).slice(0,6).map((event) => <div key={event.id} className="rounded-2xl border border-[hsl(var(--border))] bg-white/70 p-4"><div className="font-medium">{event.eventLabel}</div><div className="text-sm text-[hsl(var(--muted-foreground))]">{new Date(event.createdAt).toLocaleString()}</div></div>)}</div></SectionCard><SectionCard title="Orders requiring attention"><div className="space-y-3">{store.orders.filter((o) => ['modified','submitted'].includes(o.status)).map((order) => <div key={order.id} className="flex items-center justify-between rounded-2xl border border-[hsl(var(--border))] bg-white/70 p-4"><div><p className="font-medium">{store.getVendorById(order.vendorId)?.name} → {store.getGrocerById(order.grocerId)?.name}</p><p className="text-sm text-[hsl(var(--muted-foreground))]">{order.id}</p></div><StatusBadge>{order.status}</StatusBadge></div>)}</div></SectionCard></div></PageShell>
}
